version: '3.8'

services:
  coze-invite:
    build: .
    container_name: coze-invite
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - /dev/shm:/dev/shm
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - PYTHONUNBUFFERED=1
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: 2gb
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
 